#Main parameters
  episode_batch: 100

  #Learner parameters
  gamma: 0.99
  batch_size: 32

  target_update: 1000


  shared_update: 200

  polyak_factor_Q: 0.001

  min_replay_size: 32

  #Actors parameters
  EPS_START: 0.9
  EPS_DECAY: 200
  EPS_END: 0.01

  #Network parameters
  input_shape: 4
  n_actions: 2
  learning_rate: 0.001
  hidden_size: 256
  optimizer: "Adam"

  #parameters replay buffer
  size_buffer: 500000
  seed : 2